name: Configure Azure environment
on:
  pull_request:
    types: [labeled]

env:
  TF_VAR_location: "australiasoutheast"
  TF_VAR_resource_group_name: "cd-with-actions"
  TF_VAR_app_plan: "actions-ttt-deployment"
  TF_VAR_webapp_name: "${{ github.actor }}-ttt-app"
  TF_VAR_image_registry_url: "https://ghcr.io"
  TF_VAR_image_registry_username: ${{ github.actor }}

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'spin up environment')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform -chdir=infra init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: |
          cd infra
          terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -chdir=infra -input=false

        # On push to "main", build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        run: terraform apply -chdir=infra -auto-approve -input=false

      - uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: infra/terraform.tfstate


  destroy-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: infra/terraform.tfstate

      - name: Terraform Destroy
        run: terraform destroy -chdir=infra -auto-approve -input=false
